### ISSUE TITLE
Convert to Django

### ISSUE THREAD

**Issue by nkantar** [nkantar/Microblot#62]
- [x] Update `docs/misc` #71
- [x] Deprecate current dependencies #72
- [x] Set up Django base project as per Two Scoops #73
- [x] Set up worker #87
- [x] Start reserved subdomain list #74
- [x] Implement basic CMS based on Django sites framework #75
